### PR TITLE
Fix for #30

### LINKED ISSUE #30: Compilation notification sound cannot be changed/disabled.
The 'compileStart' notification has a sound even if the `sound` option is set to `false`.

It seems it is not affected by the `sound` option in general, and it has no option on its own.

### PR DESCRIPTION
**Pull request by DocCoding**
This PR fixes #30 and adds a new config option `compilationSound` to change/disable the compilation notification sound individually.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -74,6 +74,12 @@ var WebpackBuildNotifierPlugin = function(cfg) {
      * Set to false to play no sound for failure notifications. Takes precedence over the *sound* configuration option.
      */
     this.failureSound = cfg.hasOwnProperty('failureSound') ? cfg.failureSound : this.sound;
+    /**
+     * @cfg {String} [compilationSound='Submarine']
+     * The sound to play for compilation notifications. Defaults to the value of the *sound* configuration option.
+     * Set to false to play no sound for compilation notifications. Takes precedence over the *sound* configuration option.
+     */
+    this.compilationSound = cfg.hasOwnProperty('compilationSound') ? cfg.compilationSound : this.sound;
```
Comment (RoccoC) [inline index.js]: I'm thinking it may be a better idea for this _not_ to have a default value. This would mean users would need to explicitly set this option to get a sound with the compilation notification, but this way we aren't spamming existing users with submarine sounds on each compile. :) Thoughts?

Comment (DocCoding) [reply index.js]: If you think `false` is a better default, we can do that - but since all the other sounds use the general sound option as default, I picked that. Another reason in favor of this: Changing the `sound` option should affect **all** sounds, not just all *except* compilation notification. 
Since compilation notifications are off by default, this change will not annoy those who do not have them turned on, but for those who do it's likely a welcome change that `sound: false` now also affects compile start, and that it can be changed individually.

Comment (RoccoC) [reply index.js]: Hmm, good points. My reservation with this approach is that those who have compilation notifications enabled and typically run their builds with watch enabled will now get sounds for each compilation (which could be quite frequent!), and I know this would annoy me personally.

That said, it's easy enough to disable and I think consistency wins out here. Will merge as is, thanks again!

Comment (RoccoC) [reply index.js]: I just tried setting `sound: false` in the plugin config on my Windows 10 Pro machine, and it disabled all sounds as expected. Not working for you?

Comment (DocCoding) [reply index.js]: It wasn't on 0.1.28, that's why I made this fix.
"My reservation with this approach is that those who have compilation notifications enabled and typically run their builds with watch enabled will now get sounds for each compilation (which could be quite frequent!), and I know this would annoy me personally." This implies that the compilation notifications had no sound on your machine, but on my Win10 they did with no way to disable it, as `sound` didn't affect that.

Comment (RoccoC) [reply index.js]: Ah, gotcha! In other words, it should be working fine in 0.1.29. I'm a little slow today.

Thanks again for taking this up.
